# Generated by Django 5.2.4 on 2025-07-28 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("zip_code", models.IntegerField()),
                ("city", models.CharField(max_length=150)),
                ("street", models.CharField(max_length=150)),
                ("house_number", models.IntegerField()),
                ("appartment_number", models.IntegerField()),
                ("is_elevator", models.BooleanField()),
            ],
            options={
                "db_table": "address",
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rooms", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("hotel", "Hotel"),
                            ("apartment", "Apartment"),
                            ("house", "House"),
                            ("studio", "Studio"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="announcements.address",
                    ),
                ),
            ],
            options={
                "db_table": "announcement",
            },
        ),
    ]
