# Generated by Django 5.2.4 on 2025-07-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("views_history", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viewhistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
