# Generated by Django 5.2.4 on 2025-07-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
